import { Award, Download, FileCheck2, Loader2 } from "lucide-react";
import type { CourseRoomHook } from "../hook";

type CertificatePanelProps = { room: CourseRoomHook };

export function CertificatePanel({ room }: CertificatePanelProps) {
    const disabled = !room.courseCompleted || room.certificateGenerating;
    const label = room.certificateGenerating ? "Generando..." : room.certificateReady ? "Visualizar certificado" : "Generar certificado";
    return <div className="rounded-[24px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex items-start gap-4"><div className={`flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl ${room.certificateReady ? "bg-emerald-50 text-emerald-700" : room.courseCompleted ? "bg-amber-50 text-amber-700" : "bg-blue-50 text-blue-700"}`}>{room.certificateReady ? <FileCheck2 className="h-6 w-6" /> : <Award className="h-6 w-6" />}</div><div><h2 className="text-lg font-black text-slate-950">Certificado del curso</h2><p className="mt-1 text-sm leading-6 text-slate-500">{room.certificateReady ? "Tu certificado ya fue generado. Puedes visualizarlo cuando lo necesites." : room.courseCompleted ? "Presiona Generar certificado. Luego el botón cambiará a visualización." : "El certificado se habilitará cuando completes el 100% del curso."}</p>{!room.courseCompleted ? <p className="mt-2 text-sm font-bold text-slate-600">Progreso actual: {room.progress}%.</p> : null}{room.certificateMessage ? <p className="mt-2 text-sm font-bold text-blue-700">{room.certificateMessage}</p> : null}</div></div><div className="flex flex-col gap-2 sm:flex-row"><button type="button" disabled={disabled} onClick={() => void room.handleViewCertificate()} className="inline-flex h-11 items-center justify-center gap-2 rounded-2xl bg-emerald-600 px-5 text-sm font-bold text-white transition hover:bg-emerald-700 disabled:cursor-not-allowed disabled:opacity-60">{room.certificateGenerating ? <Loader2 className="h-4 w-4 animate-spin" /> : room.certificateReady ? <FileCheck2 className="h-4 w-4" /> : <Award className="h-4 w-4" />}{label}</button>{room.certificateFileUrl ? <a href={room.certificateFileUrl} target="_blank" rel="noreferrer" className="inline-flex h-11 items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-white px-5 text-sm font-bold text-slate-700 transition hover:bg-slate-50"><Download className="h-4 w-4" />Descargar PDF</a> : null}</div></div></div>;
}
